// Builds the single-file server the Claude Code / Codex / ChatGPT plugin ships:
// plugins/tab-state/server/tab-state-mcp.mjs
//
//   npm run build:plugin
//
// Plugins are installed by copying the plugin folder out of the git repo, with no `npm install`
// step, so the server and its dependencies (MCP SDK, zod) are bundled into one file that only
// needs Node 18+. The output is committed; its header records a hash of the sources it was built
// from, and test/plugin.test.js fails if the sources change without a rebuild.

import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const MCP_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const OUT = path.resolve(MCP_DIR, '../plugins/tab-state/server/tab-state-mcp.mjs');
export const SOURCES = ['plugin-entry.mjs', 'server.mjs', 'store.mjs', 'package-lock.json'];

export function sourceHash() {
  const h = createHash('sha256');
  for (const f of SOURCES) h.update(readFileSync(path.join(MCP_DIR, f)));
  return h.digest('hex').slice(0, 16);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  mkdirSync(path.dirname(OUT), { recursive: true });
  await build({
    entryPoints: [path.join(MCP_DIR, 'plugin-entry.mjs')],
    outfile: OUT,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node18',
    minify: true, // readable source is mcp-server/; this is ~2x smaller
    legalComments: 'eof',
    banner: {
      js: [
        `// GENERATED by mcp-server/scripts/build-plugin.mjs from mcp-server/ (source hash ${sourceHash()}).`,
        '// Do not edit: change mcp-server/server.mjs or store.mjs and run `npm run build:plugin` there.',
        "import { createRequire as __tsCreateRequire } from 'node:module';",
        'const require = __tsCreateRequire(import.meta.url);',
      ].join('\n'),
    },
  });
  console.log(`build-plugin: ${path.relative(process.cwd(), OUT)}`);
}
